# Generated by Django 3.2.6 on 2021-12-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cats',
            old_name='code',
            new_name='unitcode',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='name',
            new_name='unitname',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='year',
            new_name='yeardone',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='code',
            new_name='unitcode',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='name',
            new_name='unitname',
        ),
        migrations.RenameField(
            model_name='exams',
            old_name='year',
            new_name='yeardone',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='code',
            new_name='unitcode',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='unitname',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='year',
        ),
    ]
